Start Task for review
DavidDzgoev/c2_StartTask pull request #2
Opened 2021-11-15 23:18 UTC by DavidDzgoev

2021-11-16 10:22 UTC, kszakharov requested changes

2021-11-16 10:22 UTC, kszakharov commented on README.md
> +6. Заполнить значение `SUBNET_ID`, `SECURITY_GROUP`, `KEY_NAME` в файле `conf.py`
Это позволяет запустить мастер ноду, но после девлоя она не может запустить воркера, из-за некоректного ID подсети, потому что на ноде неизменненный файл

2021-11-16 10:24 UTC, kszakharov commented on start_master_node.sh
> +python3 regular_task.py &
Почему-то не запустилось

2021-11-16 10:25 UTC, kszakharov commented on README.md
> +7. Открыть у группы безопасности входящие правила на 22, 80, 5000 порты
А что на 80 порту работает?

2021-11-22 12:57 UTC, DavidDzgoev commented on README.md
> +7. Открыть у группы безопасности входящие правила на 22, 80, 5000 порты
убрал

2021-11-22 12:58 UTC, DavidDzgoev commented on start_master_node.sh
> +python3 regular_task.py &
работает на ubuntu, не работает на centos

2021-11-22 12:58 UTC, DavidDzgoev commented on master.py
> +        {type: requests.get(f"{METADATA_URL}{type}").text for type in METADATA_TYPES}
Реализовал функцию

2021-11-22 12:58 UTC, DavidDzgoev commented on regular_task.py
> +            return
убрал

2021-11-22 12:59 UTC, DavidDzgoev commented on README.md
> +1. По завершению работы `start_up.py` выдаст id виртуалки-мастера.
Добавил опцию выдачи ip и вывода дополнительной информации после функции start_up

2021-11-22 13:00 UTC, DavidDzgoev commented on README.md
> +6. Заполнить значение `SUBNET_ID`, `SECURITY_GROUP`, `KEY_NAME` в файле `conf.py`
Изменил конфиги, теперь актуальный конфиг через user-data передается мастеру

2021-11-22 13:34 UTC, DavidDzgoev commented on README.md
> +4. Запустить файл `start_up.py`
Изменил readme

2021-11-22 18:19 UTC, kszakharov approved these changes
Не нашел где, но  первый воркер запускается с внешним IP. Нужно поправить.

2021-11-22 18:19 UTC, kszakharov commented on start_up.py
> +    if (
Поменяй местами `if` и `else`

2021-11-22 18:20 UTC, kszakharov commented
👍

2021-11-25 10:06 UTC, No-Rib commented on regular_task.py
> +        with open("start_node.sh") as f:
В этой ветке логика такая же, как и в `/add` в мастере, может этот метод вызывать здесь? Такое ощущение, что изначально так и было запланировано

2021-11-25 10:12 UTC, No-Rib commented on regular_task.py
> +            ec2_conn.terminate_instances(instance_ids=[instance_to_rm_id])
Надо еще алармы подтереть за инстансом

2021-11-26 18:30 UTC, DavidDzgoev commented on start_up.py
> +    if (
Исправил

2021-11-26 18:31 UTC, DavidDzgoev commented on start_up.py
> +    ec2_conn = boto.connect_ec2_endpoint(
Удалил повторяющиеся коннекешены

2021-11-26 18:31 UTC, DavidDzgoev commented on start_up.py
> +    cw_conn = CloudWatchConnection(EC2_ACCESS_KEY, EC2_SECRET_KEY, region=region)
Удалил повторяющиеся коннекешены

2021-11-26 18:32 UTC, DavidDzgoev commented on regular_task.py
> +            ec2_conn.terminate_instances(instance_ids=[instance_to_rm_id])
Добавил удаление алармов

2021-11-26 18:33 UTC, DavidDzgoev commented on regular_task.py
> +        with open("start_node.sh") as f:
добавил еще   `/terminate` и теперь regular_task просто вызывает `/add` или `/terminate`

2021-11-26 18:53 UTC, DavidDzgoev commented on README.md
> +7. Запустить файл `start_up.py`
1. Добавил строчку `python3 start_up.py`. 
2. По `user_conf.py`, сейчас добавил пункт 5,  в котором пользователь должен задублировать значения из `start_master_node.sh` в `user_conf.py`. Можно полностью отделить генерацию `user_conf.py` в условный `user_conf_generation.sh`, который пользователь будет запускать. Но тогда нужно будет собирать user_data из нескольких файлов, что может сделать код менее читаемым.

2021-11-29 14:28 UTC, No-Rib commented on README.md
> +7. Запустить файл `start_up.py`
Зато конфигурация хранится в одном месте, не нужно проверять, что правки прокинуты в несколько файлов. Ну и с читаемостью особых проблем быть не должно.
Но ладно, это на будущее

2021-11-29 14:29 UTC, No-Rib approved these changes

2021-12-02 07:45 UTC, merged

2023-04-12 10:37 UTC, GETss433 commented
Давид, можешь ли ты со мной связаться? У меня для тебя есть предложение. https://vk.com/ss_433